// d4-zh.js - Diablo 4 计算器简体中文翻译
// 在 HTML 中所有其他脚本之后加载此文件
(function(){
"use strict";
var T={
"D4 Calculators":"D4 计算器",
"D4 Damage Calculator":"D4 伤害计算器",
"D4 Defense Calculator":"D4 防御计算器",
"Tools":"工具",
"Damage Calculator":"伤害计算器",
"Defense Calculator (S6 BETA)":"防御计算器 (S6 测试版)",
"Choose your calculator:":"选择计算器：",
"DAMAGE":"伤害",
"DEFENSE":"防御",
"Get help or contribute:":"获取帮助或贡献：",
"HELP / CODE":"帮助 / 代码",
"MORE D4 TOOLS":"更多 D4 工具",
"Color style dark:":"深色模式：",
"Show detailed damage:":"显示详细伤害：",
"Show detailed result:":"显示详细结果：",
"Always single column:":"始终单列显示：",
"CREATE NEW CALCULATOR":"创建新计算器",
"LOAD STORED CALCULATOR":"加载已存储的计算器",
"IMPORT FROM FILE":"从文件导入",
"TOGGLE COLOR STYLE":"切换颜色风格",
"New Calculator":"新计算器",
"Character class:":"角色职业：",
"- select -":"- 选择 -",
"Barbarian":"野蛮人",
"Druid":"德鲁伊",
"Necromancer":"死灵法师",
"Paladin":"圣骑士",
"Rogue":"游侠",
"Sorcerer":"法师",
"Spiritborn":"灵巫",
"Warlock":"术士",
"Primary weapon damage:":"主武器伤害：",
"Added weapon damage:":"附加武器伤害：",
"Total attack speed:":"总攻击速度：",
"Skill damage modifier (%):":"技能伤害修正 (%)：",
"Is damage over time:":"是否为持续伤害：",
"Damage over time duration:":"持续伤害时长：",
"Main stat (str, int, dex, wil):":"主属性(力量/智力/敏捷/意志)：",
"Damage bonus from stat (%):":"主属性伤害加成 (%)：",
"Base life:":"基础生命：",
"Max. life:":"最大生命：",
"Character is fortified:":"角色处于强固状态：",
"Damage to vulnerable ([x]%):":"对易伤伤害 ([x]%)：",
"Unlock fixed value":"解锁固定值",
"Additive damage ([+]%):":"加法伤害 ([+]%)：",
"Critical strike damage ([x]%):":"暴击伤害 ([x]%)：",
"Critical strike chance (%):":"暴击率 (%)：",
"Overpower damage ([x]%):":"压制伤害 ([x]%)：",
"Overpower damage per stack ([+]%):":"每层压制伤害 ([+]%)：",
"Active overpower stacks:":"当前压制层数：",
"Every n-th attack will overp.:":"每 n 次攻击触发压制：",
"Add new modifier":"添加新修正",
"Vulnerable enemies:":"易伤敌人：",
"Critical strike:":"暴击：",
"CALCULATE DAMAGE":"计算伤害",
"CALCULATE DEFENSE":"计算防御",
"Simulate attacks:":"模拟攻击：",
"RUN (BETA)":"运行 (测试)",
"SAVE":"保存",
"LOAD":"加载",
"EXPORT":"导出",
"IMPORT":"导入",
"CLOSE":"关闭",
"remove":"移除",
"disable":"禁用",
"Set":"设置",
"Save":"保存",
"Ok":"确定",
"Submit":"提交",
"Name:":"名称：",
"CLEAR ALL":"清除全部",
"EXPORT ALL":"导出全部",
"Bonus weapon damage":"额外武器伤害",
"Skill base damage":"技能基础伤害",
"Main stat.":"主属性。",
"Core damage after add. mod.":"加法修正后核心伤害",
"Max. damage after add. mod.":"加法修正后最大伤害",
"Core damage after multipliers":"乘数修正后核心伤害",
"Max. damage after multipliers":"乘数修正后最大伤害",
"Damage to vulnerable enemies":"对易伤敌人伤害",
"Damage with critical strike":"暴击伤害",
"Damage with overpower":"压制伤害",
"Total max. damage per hit":"每次攻击最大总伤害",
"Expected damage per hit":"每次攻击期望伤害",
"Average DPS":"平均 DPS",
"Average DPS (sim.: ":"平均 DPS(模拟：",
") ...":")...",
"Contribution of this add. value: ":"此加法值贡献：",
"Contribution of additive vulnerable damage: ":"加法易伤伤害贡献：",
"Contribution of additive critical hit damage: ":"加法暴击伤害贡献：",
"Contribution of additive overpower damage: ":"加法压制伤害贡献：",
"Standalone contribution of this multiplier with regard to previous section. Value: ":"此乘数独立贡献。值：",
"Damage contribution of this multiplier bucket. Value: ":"此乘数桶伤害贡献。值：",
"Base armor":"基础护甲",
"Total armor":"总护甲",
"Physical DR from armor (approx.)":"护甲物理减伤(约)",
"Armor required for 85% cap":"达到85%上限所需护甲",
"Base maximum life":"基础最大生命",
"Total life + barrier":"总生命+屏障",
"Total damage reduction":"总伤害减免",
"Total additional damage taken":"总额外承受伤害",
"Base effective life":"基础有效生命",
"Effective life vs elemental":"对元素有效生命",
"Effective life vs physical":"对物理有效生命",
"Enter a name for this configuration:":"输入此配置的名称：",
"Choose a configuration:":"选择配置：",
"Configuration has been saved to browser storage.":"配置已保存到浏览器存储。",
"Vulnerable Enemy":"易伤敌人",
"Vulnerable Damage Multiplier":"易伤伤害乘数",
"Critical Strike":"暴击",
"Critical Strike Damage Multiplier":"暴击伤害乘数",
"Damage Over Time":"持续伤害",
"Damage Over Time Multiplier":"持续伤害乘数",
"Requires Overpower Stacks":"需要压制层数",
"All/Phys/[Element] Damage Multi.":"全部/物理/[元素]伤害乘数",
"Simulating DPS (":"正在模拟 DPS(",
"Damage Sim. (":"伤害模拟(",
" attacks)":" 次攻击)",
"Armor base values ([+] gear, paragon, etc.):":"护甲基础值([+] 装备、巅峰等)：",
"Armor percentage modifiers ([%]):":"护甲百分比修正 ([%])：",
"Elemental resistance (lowest) [%]:":"元素抗性(最低)[%]：",
"Maximum life additive values ([+] gear, etc.):":"最大生命加法值([+] 装备等)：",
"Max. life modifiers ([%] rubies, paragon, etc.):":"最大生命修正([%] 红宝石、巅峰等)：",
"Damage reduction ([%] gear, paragon, etc.):":"伤害减免([%] 装备、巅峰等)：",
"Additional damage taken ([%] passives etc.):":"额外承受伤害([%] 被动等)：",
"Is fortified:":"强固状态：",
"Strength:":"力量：",
"Character/enemy level:":"角色/敌人等级：",
"Made by":"作者：",
"Version:":"版本：",
"Season":"赛季",
"Histogram":"直方图",
"damage":"伤害",
"count":"次数",
"Import a configuration to this calculator from file or import a whole set":"从文件导入配置到此计算器",
"Title of this calculator. Click to edit.":"计算器标题，点击可编辑。",
"Welcome to the<br>D4 Damage Calculator":"欢迎使用<br>D4 伤害计算器",
"Welcome to the<br>D4 Defense Calculator":"欢迎使用<br>D4 防御计算器",
"Toggle D4 tools menu.":"切换 D4 工具菜单。",
"Toggle display options.":"切换显示选项。",
"Save this configuration":"保存此配置",
"Load a configuration to this calculator":"加载配置到此计算器",
"Export this configuration to a file":"导出此配置到文件",
"Close this calculator":"关闭此计算器",
"Load a stored calculator and add it to the screen.":"加载已存储的计算器并添加到屏幕。",
"Create a new calculator and add it to the screen.":"创建新计算器并添加到屏幕。",
"Please use [a-zA-Z0-9\\\\\\\\s_\\\\\\\\-]":"请使用 [a-zA-Z0-9\\\\\\\\s_\\\\\\\\-]",
"Allowed characters: a-Z,0-9,_,- and space":"允许的字符：a-Z、0-9、_、- 和空格",
"Name for this modifier.":"此修正的名称。",
"Or select one from the list:":"或从列表中选择：",
"Select a name from this predefined list.":"从此预定义列表中选择名称。",
"Search Name (BETA)":"搜索名称 (测试)",
"- Select (BETA) -":"- 选择 (测试) -",
"Select required types (optional):":"选择需要的类型(可选)：",
"No data found in browser storage.<br>Please import a backup file or save a new configuration.":"浏览器存储中未找到数据。<br>请导入备份文件或保存新配置。",
"- Found no stored data for this calculator -":"- 未找到此计算器的存储数据 -",
"Delete this entry from browser storage?":"从浏览器存储中删除此条目？",
"Are you sure you want to remove ALL cached data for ALL calculators?":"确定要删除所有计算器的全部缓存数据？",
"Warning: This will overwrite existing configurations with the same name! Continue?":"警告：这将覆盖同名已有配置！继续？",
"All configurations restored from file.":"所有配置已从文件恢复。",
"Failed to read from localStorage. Error: ":"读取 localStorage 失败。错误：",
"Failed to write to localStorage. Error: ":"写入 localStorage 失败。错误：",
"Failed to edit localStorage. Error: ":"编辑 localStorage 失败。错误：",
"Tried to load calculator(s) from URL but failed.<br>Error: ":"尝试从URL加载计算器失败。<br>错误：",
"Tried to load calculator(s) from URL but failed.<br>See console for detailed error.":"尝试从URL加载计算器失败。<br>请查看控制台了解详细错误。",
"Could not import data.<br>Unknown file format.":"无法导入数据。<br>未知文件格式。",
"Failed to load visualization library!":"加载可视化库失败！",
"Loading ...":"加载中...",
"ERROR - Failed to load visualization!":"错误 - 加载可视化失败！",
"Enter a name for this '+' modifier:":"输入此+修正的名称：",
"Enter a name for this '×' modifier:":"输入此x修正的名称：",
"Enter a name for this damage reduction modifier:":"输入此伤害减免修正的名称：",
"Enter a name for this value:":"输入此值的名称：",
"Enter a name for this '%' modifier:":"输入此%修正的名称：",
"Enter a name for this penalty modifier:":"输入此惩罚修正的名称：",
"A file with calculators has been loaded.\\\\nDo you want to open/import the data?":"已加载计算器文件。\\\\n要打开/导入数据吗？",
"Deprecation note:":"弃用说明：",
"Example: Damage while Healthy":"示例：对健康敌人伤害",
"Example: Damage on Monday":"示例：周一伤害",
"Example: Grandfather Crit.":"示例：祖父暴击",
"Example: Heir of Perdition":"示例：毁灭之嗣",
"Example: Royal Skull":"示例：皇家骷髅",
"Example: Fire Damage Multi.":"示例：火焰伤害乘数",
"Monster damage reduction (lvl 70)":"怪物伤害减免(70级)",
"DR vs All":"全部减伤",
"DR vs Elite":"对精英减伤",
"DR vs Close":"对近距减伤",
"DR vs Distant":"对远距减伤",
"Pass.: Class Cannon":"被动：玻璃大炮",
"All Damage Reduction":"全部伤害减免",
"DR from ":"减伤来自 ",
"DR from Bleeding":"流血减伤",
"DR from Burning":"燃烧减伤",
"DR from CC":"控制减伤",
"DR from Chilled":"冰冻减伤",
"DR from Close":"近距减伤",
"DR from Distant":"远距减伤",
"DR from Elites":"精英减伤",
"DR from Poisoned":"中毒减伤",
"DR from Shadow DoT":"暗影持续减伤",
"DR from Slowed":"减速减伤",
"DR from Trapped":"陷阱减伤",
"DR from Vulnerable":"易伤减伤",
"DR while ":"减伤：",
"DR while Barrier":"屏障时减伤",
"DR while Fortified":"强固时减伤",
"DR while Healthy":"健康时减伤",
"All":"全部",
"Helm":"头盔",
"Chest":"胸甲",
"Gloves":"手套",
"Pants":"裤子",
"Boots":"靴子",
"Off-Hand":"副手",
"Amulet":"护符",
"Ring":"戒指",
"2h Weapon":"双手武器",
"1h Weapon":"单手武器",
"Temper: ":"淬炼：",
"Paragon Node":"巅峰节点",
"Passive: ":"被动：",
"Passive: Glass Cannon":"被动：玻璃大炮",
"All Damage Multiplier":"全部伤害乘数",
"Physical Damage Multiplier":"物理伤害乘数",
"[Element] Damage Multiplier":"[元素]伤害乘数",
"Weapon 1h: ":"单手武器：",
"Weapon 2h: ":"双手武器：",
"Gem: ":"宝石：",
"Item: ":"物品：",
"Ring: ":"戒指：",
"Gloves: ":"手套：",
"Amulet: ":"护符：",
"All Damage":"全部伤害",
"Physical Damage":"物理伤害",
"Phys. Damage Over Time":"物理持续伤害",
"[Element] Damage":"[元素]伤害",
"[Element] Damage Over Time":"[元素]持续伤害",
"Damage vs Bleeding":"对流血敌人伤害",
"Damage vs Burning":"对燃烧敌人伤害",
"Damage vs Chilled":"对冰冻敌人伤害",
"Damage vs Close":"对近距敌人伤害",
"Damage vs Crowd Controlled":"对控场敌人伤害",
"Damage vs Distant":"对远距敌人伤害",
"Damage vs Elites":"对精英伤害",
"Damage vs Healthy":"对健康敌人伤害",
"Damage vs Injured":"对受伤敌人伤害",
"Damage vs Poisoned":"对中毒敌人伤害",
"Damage vs Slowed":"对减速敌人伤害",
"Damage vs Stunned":"对昏迷敌人伤害",
"Damage while Berserking":"狂暴时伤害",
"Damage while Fortified":"强固时伤害",
"Damage while Healthy":"健康时伤害",
"Bone Crit. Damage":"骨系暴击伤害",
"Damage of your weapon(s) used to cast the skill, taken from character stats menu, OR the value of your primary damage effect like Dust Devils, Ice Spikes, Splintering Energy, etc. For skills with 1h double-swing attacks please divide the number by 2 if the skill mentions separate single-handed attacks.":"施放技能所用武器的伤害值，取自角色属性面板；或主要伤害效果的值（如尘魔、冰刺、碎裂能量等）。双持单手交替攻击的技能请除以2。",
"Damage added to the weapon(s) via gear affix. If you attack with 2 weapons take the sum of the affixes on both weapons.":"通过装备词缀附加到武器的伤害。双持时取两把武器词缀之和。",
"Attack speed found in your character stats menu (includes weapon speed and boni). Will be used for DPS calculation.":"角色属性面板中的攻击速度（含武器速度和加成）。用于计算DPS。",
"Skill damage taken from skill tree description.":"技能树描述中的技能伤害值。",
"Is the skill applying damage over time? This will take the tick duration into account.":"该技能是否造成持续伤害？将考虑每跳持续时间。",
"The duration value given for the damage over time skill, for example '... over 5s'.":"持续伤害技能的持续时间，例如\x22...持续5秒\x22。",
"Your character's primary stat (strength, dexterity, ...).":"你的角色主属性（力量、敏捷等）。",
"Damage bonus due to main stat value (calculated automatically for each class).":"基于主属性值的伤害加成（根据职业自动计算）。",
"Your base life, taken from character stats menu. Note: depends on your character level.":"角色属性面板中的基础生命值。取决于角色等级。",
"Base and maximum life. Used for example to calculate overpower damage.":"基础生命和最大生命。用于计算压制伤害等。",
"Is the character fortified?":"角色是否处于强固状态？",
"The fixed damage multiplier for vulnerable. If your gear has [x%] modifiers its recommended to add them to the global section below.":"易伤的固定伤害乘数。若装备有[x%]修正，建议添加到下方全局乘数区域。",
"Additive damage gained from 'vulnerable damage' stats on items, paragon board etc.":"来自装备、巅峰盘等的\x22易伤伤害\x22属性的加法伤害。",
"The fixed damage multiplier for crit. damage. If your gear has [x%] modifiers its recommended to add them to the global section below.":"暴击的固定伤害乘数。若装备有[x%]修正，建议添加到下方全局乘数区域。",
"Additive damage gained from 'critical damage' stats on items, paragon board etc.":"来自装备、巅峰盘等的\x22暴击伤害\x22属性的加法伤害。",
"Critical strike chance. Used for example below to calculate an average damage per hit.":"暴击率。用于计算每次攻击的平均伤害。",
"The fixed base multiplier for overpower damage. If your gear has [x%] modifiers its recommended to add them to the global section below.":"压制伤害的固定基础乘数。若装备有[x%]修正，建议添加到下方全局乘数区域。",
"The sum of all your additive damage gained from 'overpower damage per stack' stats on items, paragon board etc.":"来自装备、巅峰盘等的\x22每层压制伤害\x22属性的加法伤害总和。",
"Number of overpower stacks that are used for the damage calculation.":"用于伤害计算的压制层数。",
"Add a value here if you use a skill or mechanic that leads to a guaranteed overpower attack on every n-th cast. Will be used for DPS calculation.":"若使用每n次施放必定触发压制的技能或机制，在此填写。将用于DPS计算。",
"Modifiers include 'Damage to Healthy, Damage with Physical, Damage with Lightning, Damage to Bleeding, etc. ...":"修正包括\x22对健康敌人伤害、物理伤害、闪电伤害、对流血敌人伤害\x22等...",
"Multipliers gained from skills, synergies, unique items, sets, aspects, paragon etc. Each value is its own 'bucket'.":"来自技能、协同、暗金装备、套装、威能、巅峰等的乘数。每个值都是独立的\x22桶\x22。",
"Multipliers gained from gear modifiers, gems, etc. Common types are aggregated to one 'bucket' each.":"来自装备修正、宝石等的乘数。同类修正会聚合到同一个\x22桶\x22。",
"Any other multipliers that reduce your damage. The most important value is the one based on your own character level called 'monster visible damage reduction' (see in-game level tool tip, lvl. 60 => 97%).":"任何降低伤害的乘数。最重要的值是基于角色等级的\x22怪物可见伤害减免\x22（见游戏内等级提示，60级=>97%）。",
"Your character class. Some damage values depend on your class, e.g. the main stat (since S5).":"你的角色职业。部分伤害值取决于职业，例如主属性（自S5起）。",
"Your base armor from gear, paragon board, skulls etc. You can add single values for each item or combine values as you like.":"来自装备、巅峰盘、骷髅等的基础护甲值。可逐项添加或任意合并。",
"Additional armor through percentage modifiers. Each value will be calculated based on the sum of your base armor.":"通过百分比修正获得的额外护甲。每个值将基于基础护甲总和计算。",
"Your elemental resistance. Choose the lowest value or the element you want to calculate.":"你的元素抗性。选择最低值或要计算的元素。",
"Additional life through gear like helms, chest armor or unique items like Grandfather etc.":"通过头盔、胸甲等装备或祖父等暗金物品获得的额外生命。",
"Additional life through percentage modifiers like ruby gems, passives or unique items like Doombringer etc. Please add each ruby and each paragon node as single entry!":"通过百分比修正（如红宝石、被动或末日使者等暗金物品）获得的额外生命。请将每个红宝石和每个巅峰节点作为单独条目添加！",
"Damage reduction in percent. Add each item individually or use the combined (inverse multiplied) values from the character stats menu.":"百分比伤害减免。逐项添加或使用角色属性面板中的合并值。",
"Additional damage taken in percent. Add each item individually.":"百分比额外承受伤害。逐项添加。",
"Is the character fortified? Check this box if you did not add fortify manually to the DR section.":"角色是否处于强固状态？若未在减伤部分手动添加强固，请勾选此项。",
"Your strength. Will be applied to base armor with a factor of 1/5 (from season 6 on).":"你的力量值。将以1/5的系数应用于基础护甲（自S6起）。",
"Character/enemy level (same since S6). Affects your damage reduction obtained through armor.":"角色/敌人等级（自S6起相同）。影响通过护甲获得的伤害减免。",
"Run a simulation of N attacks and show the damage distribution and average.":"运行N次攻击模拟，显示伤害分布和平均值。",
"Select one or more required 'types' for this item to in-/exclude it in certain calculations. No 'type' means it applies to all calculations.":"选择需要的\x22类型\x22以在特定计算中包含/排除此项。无\x22类型\x22表示适用于所有计算。",
"Bonus weapon damage of active weapon(s).":"当前武器的额外武器伤害。",
"Average base damage done with the given weapon and skill.":"使用给定武器和技能的平均基础伤害。",
"Damage including main stat factor.":"包含主属性因子的伤害。",
"Core damage (no vulnerable/crit./overpower) after all additive modifiers have been applied.":"应用所有加法修正后的核心伤害（不含易伤/暴击/压制）。",
"Max. damage for most powerful hit, after all additive modifiers have been applied.":"应用所有加法修正后最强一击的最大伤害。",
"Core damage (no vulnerable/crit./overpower) after all additive and multiplicative modifiers have been applied.":"应用所有加法和乘法修正后的核心伤害（不含易伤/暴击/压制）。",
"Max. damage for most powerful hit, after all additive and multiplicative modifiers have been applied (except the separate base multipliers for vuln./crit./overp.).":"应用所有加法和乘法修正后最强一击的最大伤害（不含易伤/暴击/压制的独立基础乘数）。",
"Total max. damage possible per hit with all the given modifiers combined (now including the base multipliers for vuln./crit./overp.), but before any damage reduction penalties.":"结合所有给定修正后每次攻击可能的最大总伤害（含易伤/暴击/压制的基础乘数），但不含伤害减免惩罚。",
"Final result for single (best) hit damage to monsters based on your average weapon damage.\n":"基于平均武器伤害对怪物的单次（最佳）伤害最终结果。\n",
"Average damage per second, if you cast the skill as fast as possible over a few seconds without resource issues.":"以最快速度施放技能且无资源问题的每秒平均伤害。",
"Includes critical strike chance and every n-th overpower hit, if check-boxes are selected.":"若勾选相应选项，包含暴击率和每n次压制攻击。",
"Damage done with critical strikes compared to regular damage (not vulnerable, no overpower) including all crit. modifiers.":"暴击伤害对比普通攻击（非易伤、无压制），包含所有暴击修正。",
"Damage done with overpower hits without modifiers like crit. or vulnerable, but including previous modifiers for type overpower.":"压制伤害（不含暴击/易伤修正），但包含压制类型的前序修正。",
"Contribution of this item.":"此物品的贡献。",
"Life determined by your character level.":"由角色等级决定的生命值。",
"Life after additional flat life boni.":"应用额外固定生命加成后的生命。",
"Total max. life after multiplicative modifiers including barrier.":"应用乘法修正后包含屏障的总最大生命。",
"Flat contribution of the modifier at this specific point in the calculation (depends on the order).":"此修正在计算中该特定点的固定贡献（取决于顺序）。",
"Base armor resulting from gear, gems, strength and paragon etc.":"来自装备、宝石、力量和巅峰等的基础护甲。",
"Total armor including all modifiers.":"包含所有修正的总护甲。",
"Physical damage reduction based on total armor and enemy level.":"基于总护甲和敌人等级的物理伤害减免。",
"Total damage penalty applying all percentages.":"应用所有百分比后的总伤害惩罚。",
"Effective life with all defense properties applied.":"应用所有防御属性后的有效生命。",
"Effective life vs selected elemental attacks with all defense properties applied.":"应用所有防御属性后对所选元素攻击的有效生命。",
"Effective life against physical attacks with all defense properties applied.":"应用所有防御属性后对物理攻击的有效生命。",
"Total damage reduction applying all percentages.":"应用所有百分比后的总伤害减免。",
"Add new value":"添加新值",
"Select required 'types' (optional):":"选择需要的\x22类型\x22（可选）：",
"Select this value to make '":"选择此项使'",
"Unnamed Calculator":"未命名计算器",
"Welcome to the":"欢迎使用",
"Unique/Set/Aspect/Paragon Multiplier":"暗金/套装/威能/巅峰乘数",
"Overpower:":"压制：",
"Avg. base dmg. with crit chance":"含暴击率的平均基础伤害",
"Configuration '":"配置 '",
"Additive damage ([+]% damage to ...):":"加法伤害（[+]% 对...伤害）：",
"Damage multipliers ([×]% Uniques/Sets/Paragon/etc.):":"伤害乘数（[×]% 暗金/套装/巅峰等）：",
"Aggregated multipliers ([×]% Gear Modifiers/Gems):":"聚合乘数（[×]% 装备修正/宝石）：",
"Damage reduction ([×]%):":"伤害减免 ([×]%)：",
"Aspect: ":"威能：",
"Charm: ":"护符：",
"Glyph: ":"雕文：",
"Glyph leg. bonus: ":"雕文传奇加成：",
"Glyph leg. bonus: %vuln":"雕文传奇加成：%易伤",
"Glyph leg. bonus: %crit":"雕文传奇加成：%暴击",
"Glyph leg. bonus: %overp":"雕文传奇加成：%压制",
"Key Pass.: ":"关键被动：",
"Leg. Node: ":"传奇节点：",
"Pass.: ":"被动：",
"Rune: ":"符文：",
"Sigil: ":"梦魇徽记：",
"Skill: ":"技能：",
"Talisman: ":"护身符：",
"Enchant.: ":"附魔：",
"BotD: ":"血潮：",
"Spec.: ":"专精：",
"Spirit Boon: ":"灵体恩惠：",
"Weapon Expertise: ":"武器专精：",
"Mercenary: ":"佣兵：",
"Elixir: ":"药剂：",
"Necro":"死灵法师",
"Sorc":"法师",
"Berserking":"狂暴",
"Ruby":"红宝石",
"Aspect: Adaptability":"威能：适应",
"Aspect: Conceited":"威能：自负",
"Aspect: Edgemasters":"威能：刃主",
"Aspect: Inner Calm":"威能：内心平静",
"Aspect: Moonrise":"威能：月升",
"Aspect: Vehement Brawler":"威能：狂热斗士",
"Aspect: Ancestral Force":"威能：先祖之力",
"Aspect: Delayed Extinction":"威能：延迟灭绝",
"Aspect: Dire Whirlwind":"威能：恐怖旋风",
"Aspect: Dust Devil":"威能：尘魔",
"Aspect: Earthquakes":"威能：地震",
"Aspect: Earthstriker":"威能：地击者",
"Aspect: Executioner":"威能：刽子手",
"Aspect: Encroaching Wrath":"威能：侵蚀之怒",
"Aspect: Herculean Spec.":"威能：赫拉克勒斯之威",
"Aspect: Incendiary Fissures":"威能：燃烧裂隙",
"Aspect: Limitless Rage":"威能：无限怒火",
"Aspect: Storm Swell":"威能：风暴涌动",
"Aspect: Three Curses":"威能：三重诅咒",
"Mercenary: Aldkin":"佣兵：奥德金",
"Mercenary: Raheir":"佣兵：拉赫尔",
"Mercenary: Subo":"佣兵：苏波",
"Mercenary: Varyana":"佣兵：瓦里亚娜",
"Mythic Unique: Ahavarion":"神话暗金：阿哈瓦里昂",
"Mythic Unique: Heir of Perdition":"神话暗金：毁灭之嗣",
"Mythic Unique: Grandfather":"神话暗金：祖父",
"Mythic Unique: Ring of Starless Sk.":"神话暗金：无星夜空之戒",
"Weapon Expertise: 2h Axe":"武器专精：双手斧",
"Weapon Expertise: 2h Mace":"武器专精：双手锤",
"Weapon Expertise: 2h Polearm":"武器专精：双手长柄",
"Glyph: Charged":"雕文：充能",
"Glyph: Control":"雕文：控制",
"Glyph: Destruction":"雕文：毁灭",
"Glyph: Elementalist":"雕文：元素使",
"Glyph: Exploit":"雕文：利用",
"Glyph: Flamefeeder":"雕文：烈焰供养",
"Glyph: Pyromaniac":"雕文：纵火狂",
"Glyph: Tactician":"雕文：战术家",
"Glyph: Torch":"雕文：火炬",
"Glyph: Unleash":"雕文：释放",
"Glyph: Winter":"雕文：寒冬",
"Glyph: Ambidextrous":"雕文：双巧手",
"Glyph: Brawl":"雕文：搏斗",
"Glyph: Challenger":"雕文：挑战者",
"Glyph: Cleaver":"雕文：劈砍者",
"Glyph: Crusher":"雕文：粉碎者",
"Glyph: Executioner":"雕文：刽子手",
"Glyph: Imbiber":"雕文：饮者",
"Glyph: Ire":"雕文：愤怒",
"Glyph: Marshall":"雕文：统帅",
"Glyph: Might":"雕文：力量",
"Glyph: Revenge":"雕文：复仇",
"Glyph: Rumble":"雕文：轰鸣",
"Glyph: Twister":"雕文：旋风",
"Glyph: Wrath":"雕文：怒火",
"Leg. Node: Blood Rage":"传奇节点：血怒",
"Leg. Node: Carnage":"传奇节点：屠杀",
"Leg. Node: Decimator":"传奇节点：歼灭者",
"Leg. Node: Flawless Technique":"传奇节点：无瑕技法",
"Leg. Node: Force of Nature":"传奇节点：自然之力",
"Leg. Node: Hemorrhage":"传奇节点：出血",
"Leg. Node: Weapons Master":"传奇节点：武器大师",
"Leg. Node: Elem. Summoner":"传奇节点：元素召唤者",
"Leg. Node: Enachant. Master":"传奇节点：附魔大师",
"Leg. Node: Frigid Fate":"传奇节点：冰冷命运",
"Leg. Node: Ice Fall":"传奇节点：冰坠",
"Leg. Node: Searing Heat":"传奇节点：灼热",
"Skill: Call of the Ancients":"技能：先祖召唤",
"Skill: Enhanced Lunging Strike":"技能：强化突刺打击",
"Skill: Furious Upheaval":"技能：狂怒动荡",
"Skill: Furious HotA":"技能：狂怒先祖之锤",
"Skill: Violent HotA":"技能：暴力先祖之锤",
"Skill: Violent Whirlwind":"技能：暴力旋风斩",
"Skill: War Cry":"技能：战吼",
"Skill: Warrior's Mighty Throw":"技能：战士强力投掷",
"Skill: Wrath o.t. Berserker":"技能：狂战士之怒",
"Item: Banished Lords":"物品：放逐领主",
"Item: Crown of Lucion":"物品：卢西恩之冠",
"Item: Fists of Fate":"物品：命运之拳",
"Item: Godslayer Crown":"物品：弑神者之冠",
"Item: Locran's Talisman":"物品：洛克兰的护身符",
"Item: Paingorgers":"物品：痛苦吞噬者",
"Item: Shard of Verathiel":"物品：维拉希尔碎片",
"Item: Tibaults Will":"物品：提博的意志",
"Item: Bane of Ahjad-Den":"物品：阿贾德-登之灾",
"Item: Chainscourged Mail":"物品：链刑锁甲",
"Item: Gohr's Dev. Grips":"物品：戈尔的毁灭之握",
"Item: Hooves of the MG":"物品：高山之怒蹄铁",
"Item: Mantle of Mountain's Fury":"物品：山怒披肩",
"Item: Ramaladni's":"物品：拉玛兰迪",
"Item: Ring of Red Furor":"物品：赤红狂怒之戒",
"Item: Sabre of Tsasgal":"物品：萨斯加之刃",
"Item: Tuskhelm":"物品：獠牙盔",
"Item: Ugly Bastard Helm":"物品：丑陋杂种盔",
"Item: Orsivane":"物品：奥西凡",
"Item: Staff of Endless Ra.":"物品：无尽怒火法杖",
"Item: Tal Rashas":"物品：塔拉夏",
"Set: ":"套装：",
"Approx. add. armor required to reach 85% DR cap.":"达到85%减伤上限所需的约额外护甲。",
"Additive damage gained from 'overpower damage' stats on items, paragon board etc.":"来自装备、巅峰盘等的压制伤害属性的加法伤害。",
"Damage to vulnerable":"对易伤伤害",
"Critical hit damage":"暴击伤害",
"Overpower dmg. (active stacks)":"压制伤害(当前层数)",
"Base life":"基础生命",
"Damage to vulnerable enemies compared to a regular strike (no crit, no overpower) including all vulnerable modifiers. ":"对易伤敌人的伤害（对比普通攻击，无暴击/压制），包含所有易伤修正。",
"Average damage of a critical hit (not vulnerable, no overpower), factoring in the critical hit chance, ":"在考虑暴击率的情况下，（非易伤、无压制的）暴击平均伤害，",
"e.g. 30% crit chance means (70% core damage + 30% crit damge).":"例如 30% 暴击率意味着 (70% 核心伤害 + 30% 暴击伤害)。",
"Max. damage after this and all previous reduction factors have been applied.":"应用此及之前所有减免因子后的最大伤害。",
"Note: Your in-game numbers can be around 25% lower/higher, depending on your min/max damage roll for weapon and skill at cast.":"注意：游戏内数值可能上下浮动约 25%，取决于武器和技能施放时的最小/最大伤害波动。",
"Contribution of additive vulnerable damage: ":"易伤加法伤害贡献：",
"Contribution of additive critical hit damage: ":"暴击加法伤害贡献：",
"Contribution of additive overpower damage: ":"压制加法伤害贡献：",
"Base factor: ":"基础因子：","Effective factor: ":"有效因子：","effective factor: ":"有效因子：",
"Average damage of a critical hit (not vulnerable, no overpower), factoring in the critical hit chance, e.g. 30% crit chance means (70% core damage + 30% crit damge).":"在考虑暴击率的情况下，（非易伤、无压制的）暴击平均伤害，例如 30% 暴击率意味着 (70% 核心伤害 + 30% 暴击伤害)。",
"Average damage per second, if you cast the skill as fast as possible over a few seconds without resource issues. Includes critical strike chance and every n-th overpower hit, if check-boxes are selected.":"以最快速度施放技能且无资源问题的每秒平均伤害。若勾选相应选项，包含暴击率和每 n 次压制攻击。",
"Final result for single (best) hit damage to monsters based on your average weapon damage.\nNote: Your in-game numbers can be around 25% lower/higher, depending on your min/max damage roll for weapon and skill at cast.":"基于平均武器伤害对怪物的单次（最佳）伤害最终结果。\n注意：游戏内数值可能上下浮动约 25%，取决于武器和技能施放时的最小/最大伤害波动。",
};

function tx(t){
if(!t||typeof t!=="string")return t;
if(T.hasOwnProperty(t))return T[t];
var ks=Object.keys(T).sort(function(a,b){return b.length-a.length;});for(var i=0;i<ks.length;i++){var k=ks[i];if(T.hasOwnProperty(k)&&t.indexOf(k)===0){var r=t.slice(k.length);if(r.length>0)return T[k]+tx(r);return T[k];}}
// Retry after stripping "+ " prefix (used in result display)
if(t.indexOf("+ ")==0){var s=t.slice(2);if(T.hasOwnProperty(s))return "+ "+T[s];for(var k in T){if(T.hasOwnProperty(k)&&s.indexOf(k)===0)return "+ "+T[k]+s.slice(k.length);}}
// Retry after stripping "x " prefix (used in multiplicative result display)
if(t.indexOf("× ")==0){var s=t.slice(2);if(T.hasOwnProperty(s))return "× "+T[s];for(var k in T){if(T.hasOwnProperty(k)&&s.indexOf(k)===0)return "× "+T[k]+s.slice(k.length);}}
return t;
}
function tn(n){
if(n.nodeType===3){var x=tx(n.textContent);if(x!==n.textContent)n.textContent=x;}
else if(n.nodeType===1&&n.tagName!=="SCRIPT"&&n.tagName!=="STYLE"){
if(n.hasAttribute("title")){var x=tx(n.getAttribute("title"));if(x!==n.getAttribute("title"))n.setAttribute("title",x);}
if(n.hasAttribute("placeholder")){var x=tx(n.getAttribute("placeholder"));if(x!==n.getAttribute("placeholder"))n.setAttribute("placeholder",x);}
var v=n.getAttribute("value");
if(v&&((n.tagName==="INPUT"&&(n.type==="button"||n.type==="submit"))||n.tagName==="BUTTON")){var x=tx(v);if(x!==v)n.setAttribute("value",x);}
}
}
function wd(r){var w=document.createTreeWalker(r,NodeFilter.SHOW_ALL,null,false);var n;while(n=w.nextNode())tn(n);}
var obs=new MutationObserver(function(ms){ms.forEach(function(m){m.addedNodes.forEach(function(n){if(n.nodeType===1)wd(n);else if(n.nodeType===3)tn(n);});});setTimeout(function(){ms.forEach(function(m){if(m.target&&m.target.nodeType===1)wd(m.target);});},50);});
var _cf=window.confirm;window.confirm=function(m){return _cf(tx(m));};
function wf(){
var _s=window.showPopUp;if(_s)window.showPopUp=function(c,b,o){if(typeof c==="string")c=tx(c);return _s(c,b,o);};
var _sf=window.showFormPopUp;if(_sf)window.showFormPopUp=function(f,os){var tf=f.map(function(fl){var x={};for(var k in fl)x[k]=fl[k];if(x.label)x.label=tx(x.label);if(x.title)x.title=tx(x.title);if(x.name&&(x.submit||x.customButton))x.name=tx(x.name);return x;});return _sf(tf,os);};
var _ad=window.addDynamicModPromptPromise;if(_ad)window.addDynamicModPromptPromise=function(iv,pt,sl,st,ps,cf){return _ad(iv,tx(pt),sl,st,ps,cf);};
}
function tl(){
var na=["additiveDamageLabelsList","multiplicativeDamageLabelsList","multiplicativeDamageLabelsListC2","flatArmorLabelsList","pctArmorLabelsList","flatLifeLabelsList","pctLifeLabelsList","damageReductionLabelsList","pctMoreDamageTakenLabelsList"];
na.forEach(function(nm){if(window[nm]&&Array.isArray(window[nm])){window[nm].forEach(function(it){if(it.label)it.label=tx(it.label);});}});
if(typeof selectableDamageTypes!=="undefined"&&Array.isArray(selectableDamageTypes)){selectableDamageTypes.forEach(function(it){if(it.name)it.name=tx(it.name);});}
}
function init(){
wd(document.body);
wf();
tl();
obs.observe(document.body,{childList:true,subtree:true,attributes:true,attributeFilter:["title"]});
}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);
else init();

})();